name: test3
on: workflow_dispatch

jobs:
  build:
     runs-on: ubuntu-latest
     
     steps:

      - name: Checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: Setup python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.9

      - name: Install python packages
        run: |
          python3 -m pip install --upgrade pip wheel
          pip3 install "setuptools<59" 
          pip install -r requirements.txt
  
      - name: Run the scraper
        run: python main.py 
